apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  selector:
    app: authservice
  ports:
    - port: 80
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: svsshivaprasad/authservice
          ports:
            - containerPort: 4000
          env:
            - name: MongoConnection
              value: mongodb://mongo:27017/test
          imagePullPolicy: Never
